# Generated by Django 2.2.5 on 2021-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='BoothName')),
                ('picture', models.ImageField(upload_to='static/img/')),
                ('description', models.TextField(verbose_name='detail')),
                ('area', models.FloatField(verbose_name='area')),
                ('price', models.FloatField(verbose_name='price')),
                ('position', models.CharField(max_length=64, verbose_name='position')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='online time')),
            ],
            options={
                'verbose_name': 'booth',
                'verbose_name_plural': 'booth',
                'ordering': ('-create_at',),
            },
        ),
    ]
