# Generated by Django 2.2.5 on 2021-02-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20210201_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='status',
            field=models.CharField(choices=[('wait to rent', 'wait to rent'), ('rented', 'rented')], default='wait to rent', max_length=32, verbose_name='status'),
        ),
    ]
