# Generated by Django 2.2.5 on 2021-02-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_auto_20210202_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delay',
            name='rent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.Rent', verbose_name='rent info'),
        ),
    ]
