# Generated by Django 2.2.5 on 2021-01-19 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='BoothName')),
                ('pictrue', models.ImageField(upload_to='static/img/')),
                ('description', models.TextField(verbose_name='about booth')),
                ('area', models.FloatField(verbose_name='area')),
                ('price', models.FloatField(verbose_name='price')),
                ('position', models.CharField(max_length=64, verbose_name='price')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='online time')),
            ],
            options={
                'verbose_name': 'booth',
                'verbose_name_plural': 'booth',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='booth_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12, verbose_name='status')),
                ('type', models.CharField(max_length=12, verbose_name='type')),
                ('time', models.IntegerField(verbose_name='length of lease')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='deadline')),
                ('booth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth', verbose_name='booth id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'status',
                'ordering': ('type', '-deadline'),
            },
        ),
        migrations.CreateModel(
            name='delay_booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='restart time')),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='deadline')),
                ('rent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth_status', verbose_name='rent id')),
            ],
            options={
                'verbose_name': 'delay booth',
                'verbose_name_plural': 'delay booth',
                'ordering': ('-deadline',),
            },
        ),
    ]
