# Generated by Django 2.2.5 on 2021-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='position',
            field=models.CharField(max_length=64, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='status',
            field=models.CharField(choices=[('checking', 'checking'), ('pass', 'pass'), ('refused', 'refused'), ('uncheck', 'uncheck')], default='uncheck', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='type',
            field=models.CharField(choices=[('rented', 'rented'), ('renting', 'renting'), ('delay', 'delay')], default='renting', max_length=12, verbose_name='type'),
        ),
    ]
