# Generated by Django 2.2.5 on 2021-01-23 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20210121_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth_status',
            name='booth_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booth.booth', verbose_name='booth id'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='deadline',
            field=models.DateTimeField(null=True, verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='status',
            field=models.CharField(choices=[('checking', 'checking'), ('pass', 'pass'), ('refused', 'refused'), ('uncheck', 'uncheck')], default='uncheck', max_length=12, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='time',
            field=models.IntegerField(null=True, verbose_name='length of lease'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='type',
            field=models.CharField(choices=[('rented', 'rented'), ('renting', 'renting'), ('delay', 'delay')], default='renting', max_length=12, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='booth_status',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='delay_booth',
            name='deadline',
            field=models.DateTimeField(verbose_name='deadline'),
        ),
    ]
