# Generated by Django 2.2.5 on 2021-01-24 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0003_auto_20210123_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checking', 'checking'), ('pass', 'pass'), ('refused', 'refused'), ('uncheck', 'uncheck')], default='uncheck', max_length=12, null=True, verbose_name='status')),
                ('unsubscribe_time', models.DateTimeField(null=True, verbose_name='unsubscribe_time')),
                ('booth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth_status', verbose_name='rent id')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'unsubscribe_booth',
                'ordering': ('-unsubscribe_time',),
            },
        ),
        migrations.DeleteModel(
            name='delay_booth',
        ),
    ]
