# Generated by Django 2.2.5 on 2021-01-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_auto_20210124_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribe',
            name='booth_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth', verbose_name='rent id'),
        ),
    ]
