# Generated by Django 2.2.5 on 2021-01-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20210124_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribe',
            name='status',
            field=models.CharField(choices=[('unsubscribe checking', 'unsubscribe checking'), ('unsubscribe pass', 'unsubscribe pass'), ('unsubscribe refused', 'unsubscribe refused'), ('unsubscribe uncheck', 'unsubscribe uncheck')], default='unsubscribe uncheck', max_length=12, null=True, verbose_name='status'),
        ),
    ]
