# Generated by Django 2.2.5 on 2021-01-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_auto_20210124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribe',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booth.booth_status', verbose_name='booth id'),
        ),
    ]
