# Generated by Django 2.2.5 on 2021-01-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_unsubscribe_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='create_at',
            field=models.DateTimeField(verbose_name='online time'),
        ),
    ]
