# Generated by Django 2.2.5 on 2021-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_auto_20210125_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='online time'),
        ),
    ]
