# Generated by Django 2.2.5 on 2021-01-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_auto_20210125_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribe',
            name='status',
            field=models.CharField(choices=[('unsubscribe checking', 'unsubscribe checking'), ('unsubscribe pass', 'unsubscribe pass'), ('unsubscribe refused', 'unsubscribe refused'), ('unsubscribe uncheck', 'unsubscribe uncheck')], default='unsubscribe uncheck', max_length=28, null=True, verbose_name='status'),
        ),
    ]
